---
version: "2.1"
services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    network_mode: "bridge"
    command: serve
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 23 * * *
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      - DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true
      - DIUN_NOTIF_GOTIFY_ENDPOINT=${GOTIFY_ENDPOINT}
      - DIUN_NOTIF_GOTIFY_TOKEN=${GOTIFY_TOKEN}
      - DIUN_WATCH_FIRSTCHECKNOTIF=true
    volumes:
      - diun-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin:latest
    network_mode: "bridge"
    container_name: jellyfin
    user: 1000:1000
    ports:
      - 8096:8096
      - 8920:8920
    volumes:
      - jellyfin-data:/config
      - jellyfin-cache:/cache
      - ${NMEDIA}:/media
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:v0.21.188-ls109
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    ports:
      - 9117:9117
    volumes:
      - jackett-data:/config
      - ${NDOWNLOADS}/seedbox:/downloads
    labels:
      - "diun.enable=false"
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=$TZ
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped

  handbrake:
    image: jlesage/handbrake:latest
    container_name: handbrake
    environment:
      - AUTOMATED_CONVERSION_PRESET=CQ22 1080p30
      - AUTOMATED_CONVERSION_FORMAT=mp4
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR=SAME_AS_SRC
      - AUTOMATED_CONVERSION_PRESET_2=CQ20 720p30
      - AUTOMATED_CONVERSION_FORMAT_2=mp4
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR_2=SAME_AS_SRC
      - AUTOMATED_CONVERSION_PRESET_3=General/Fast 480p30
      - AUTOMATED_CONVERSION_FORMAT_3=mp4
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR_3=SAME_AS_SRC
    ports:
      - 5800:5800
    volumes:
      - handbrake-data:/config
      - ${NMEDIA}:/storage/zfs:ro
      - ${NX}:/storage/blue:ro
      - ${NHANDBRAKE}/watch1080:/watch
      - ${NHANDBRAKE}/watch720:/watch2
      - ${NHANDBRAKE}/watch480:/watch3
      - ${NHANDBRAKE}/output:/output
    restart: unless-stopped

  rutorrent:
    image: crazymax/rtorrent-rutorrent:4.2.5-0.9.8-0.13.8
    container_name: rutorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - RUTORRENT_PORT=8091
      - XMLRPC_PORT=5000
      - RT_INC_PORT=51413
    ports:
      - 8091:8091             # web ui
      - 5000:5000             # scgi socket
      - 51413:51413           # incoming connections
      - 6881:6881/udp
    volumes:
      - rutorrent-data:/data
      - ${NDOWNLOADS}/rutorrent:/downloads
    restart: unless-stopped

  calibre:
    image: linuxserver/calibre:v6.20.0-ls223
    container_name: calibre
    # security_opt:
      # - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      # - PASSWORD= #optional
      # - CLI_ARGS= #optional
    ports:
      - 8084:8080
      - 8085:8081
    volumes:
      - calibre-data:/config
      - ${NMEDIA}/books:/books
      - ${NDOWNLOADS}/rutorrent/complete:/downloads
    restart: unless-stopped

  calibre-web:
    image: linuxserver/calibre-web:0.6.20-ls214
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      # - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      # - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    ports:
      - 8083:8083
    volumes:
      - calibre-web-data:/config
      - ${NMEDIA}/books:/books
    restart: unless-stopped

volumes:
  diun-data:
    name: diun-data
  jellyfin-data:
    name: jellyfin-data
  jellyfin-cache:
    name: jellyfin-cache
  jackett-data:
    name: jackett-data
  radarr-data:
    name: radarr-data
  handbrake-data:
    name: handbrake-data
  rutorrent-data:
    name: rutorrent-data
  calibre-data:
    name: calibre-data
  calibre-web-data:
    name: calibre-web-data
