---
version: "2.1"
services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    hostname: diun-svchost
    network_mode: "bridge"
    command: serve
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 23 * * *
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      - DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true
      - DIUN_NOTIF_GOTIFY_ENDPOINT=${GOTIFY_ENDPOINT}
      - DIUN_NOTIF_GOTIFY_TOKEN=${GOTIFY_TOKEN}
      - DIUN_WATCH_FIRSTCHECKNOTIF=true
      - DIUN_WATCH_HEALTHCHECKS_BASEURL=${HEALTHCHECKS_URL}
      - DIUN_WATCH_HEALTHCHECKS_UUID=${HEALTHCHECKS_UUID}
    volumes:
      - diun-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_HOST=${DB_HOST}
    ports:
      - 8009:80
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:2.14.2
    network_mode: "bridge"
    container_name: portainer
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: unless-stopped

volumes:
  diun-data:
    name: diun-data
  portainer-data:
    name: portainer-data
