---
version: "2.1"
services:
  proxy:
    image: jc21/nginx-proxy-manager:2.9.22
    network_mode: "bridge"
    container_name: proxy
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - npm-data:/data
      - ${DOCKER_APP_DATA}/npm-letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  homer:
    image: b4bz/homer:latest
    network_mode: "bridge"
    container_name: homer
    environment:
      - UID=1000
      - GID=1000
    ports:
      - 8080:8080
    volumes:
      - ${DOCKER_APP_DATA}/homer:/www/assets
    restart: unless-stopped 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_HOST=${DB_HOST}
    ports:
      - 8009:80
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:2.14.2
    network_mode: "bridge"
    container_name: portainer
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: unless-stopped

  diun:
    image: crazymax/diun:latest
    container_name: diun
    network_mode: "bridge"
    command: serve
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 23 * * *
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      - DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true
      - DIUN_NOTIF_GOTIFY_ENDPOINT=${GOTIFY_ENDPOINT}
      - DIUN_NOTIF_GOTIFY_TOKEN=${GOTIFY_TOKEN}
      - DIUN_WATCH_FIRSTCHECKNOTIF=true
      - DIUN_WATCH_HEALTHCHECKS_BASEURL=${HEALTHCHECKS_URL}
      - DIUN_WATCH_HEALTHCHECKS_UUID=${HEALTHCHECKS_UUID}
    volumes:
      - diun-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  npm-data:
    name: npm-data
  mariadb-data:
    name: mariadb-data
  portainer-data:
    name: portainer-data
  diun-data:
    name: diun-data
