---
version: "2.1"
services:
  proxy:
    image: jc21/nginx-proxy-manager:2.9.22
    network_mode: "bridge"
    container_name: proxy
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - npm-data:/data
      - ${DOCKER_APP_DATA}/npm-letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  homer:
    image: b4bz/homer:latest
    network_mode: "bridge"
    container_name: homer
    environment:
      - UID=1000
      - GID=1000
    ports:
      - 8080:8080
    volumes:
      - ${DOCKER_APP_DATA}/homer:/www/assets
    restart: unless-stopped 

  mariadb:
    image: lscr.io/linuxserver/mariadb:10.5.17
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/config
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8008:80
    depends_on:
      - mariadb
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:2.14.2
    network_mode: "bridge"
    container_name: portainer
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: unless-stopped

volumes:
  npm-data:
    name: npm-data
  mariadb-data:
    name: mariadb-data
  portainer-data:
    name: portainer-data
