---
version: "2.1"
services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    hostname: diun-nextpvr
    network_mode: "bridge"
    command: serve
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 23 * * *
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      - DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true
      - DIUN_NOTIF_GOTIFY_ENDPOINT=${GOTIFY_ENDPOINT}
      - DIUN_NOTIF_GOTIFY_TOKEN=${GOTIFY_TOKEN}
      - DIUN_WATCH_FIRSTCHECKNOTIF=true
    volumes:
      - diun-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  nextpvr:
    image: nextpvr/nextpvr_amd64:stable
    container_name: nextpvr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - nextpvr-config:/config
      - ${NMEDIA}/tv/recordings:/recordings
      - ${NMEDIA}/tv/.nextpvr/buffer:/buffer
    ports:
      - 8866:8866
    restart: unless-stopped

volumes:
  diun-data:
    name: diun-data
  nextpvr-config:
    name: nextpvr-config
